# Generated by Django 6.1.2 on 2026-10-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('servicio', models.IntegerField()),
                ('hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
